### ISSUE TITLE
`auxclick` example missing viewport

### ISSUE THREAD

**Issue by MrBrain295** [mdn/dom-examples#135] opened 2022-07-11 20:53 UTC
The `auxclick` example has the font size relative to the viewport but the viewport isn’t defined.

**Comment by zfox23** [comment] 2023-11-16 15:40
The width of the viewport within the context of an `<iframe>` is the width of the `<iframe>`. In [the `auxclick` example](https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event#html), the width of the `<iframe>` _is_ defined as `calc(100% - 2rem - 2px)`. The button's text font size is set to `8vw`, which does seem to be computed properly.

Because this seems to be working as intended, I"m going to close this issue. If I am misunderstanding this bug, please feel free to re-open the issue. Thanks!

**Closed by zfox23** 2023-11-16 15:40 UTC
Labels: bug, area: auxclick
