### ISSUE TITLE
basic example returns "NetworkError when attempting to fetch resource."

### ISSUE THREAD

**Issue by bcag2** [mdn/dom-examples#152] opened 2022-03-09 10:57 UTC
I clone this projects and try run _basic-fetch_ example, as my first test, Firefox returns "NetworkError when attempting to fetch resource." Similar error with Chromium : "Error: Failed to fetch"

I use Ubuntu 18.04 and firefox v97.0.2 and chromium v99

EDIT : 
this example works fine (src (fr language) : https://www.digitalocean.com/community/tutorials/how-to-use-the-javascript-fetch-api-to-get-data-fr ):  
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Fetch basic example</title>

    <link rel="stylesheet" href="">
  </head>

  <body>
<h1>Authors</h1>
<ul id="authors"></ul>

  </body>
<script>
function createNode(element) {
    return document.createElement(element);
}

function append(parent, el) {
  return parent.appendChild(el);
}

const ul = document.getElementById('authors');
const url = 'https://randomuser.me/api/?results=10';

fetch(url)
.then((resp) => resp.json())
.then(function(data) {
  let authors = data.results;
  return authors.map(function(author) {
    let li = createNode('li');
    let img = createNode('img');
    let span = createNode('span');
    img.src = author.picture.medium;
    span.innerHTML = `${author.name.first} ${author.name.last}`;
    append(li, img);
    append(li, span);
    append(ul, li);
  })
})
.catch(function(error) {
  console.log(error);
});
</script>
</html>
```

**Comment by bsmth** [comment] 2023-11-23 09:58
Thanks for reporting @bcag2, the answer is above:

>CORS prevents you from making such fetches from `file://`. You must serve this page through a server (in `http://`).

And is specifically this behavior: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSRequestNotHttp#loading_a_local_file

To see the working example using [Python's built-in HTTP server](https://docs.python.org/3/library/http.server.html), try the following steps:

```bash
git clone https://github.com/mdn/dom-examples.git
cd dom-examples/fetch/basic-fetch
python3 -m http.server
```

open http://localhost:8000/ and you should see the example as expected. I'm going to close this as can't reproduce, but if you are still having trouble, feel free to reply. Thank you :)

**Closed by bsmth** 2023-11-23 09:58 UTC
Labels: area: fetch, cors, limitation
