### ISSUE TITLE
Service worker example does not work (404 Not Found)

### ISSUE THREAD

**Issue by tetradice** [mdn/dom-examples#176] opened 2022-09-27 00:13 UTC
I tried this demo: https://mdn.github.io/dom-examples/service-worker/simple-service-worker/

But service worker was not found and not installed.
![image](https://user-images.githubusercontent.com/802975/192402505-a0b1b148-09ae-4da3-968e-eb9958a2e54b.png)

**Comment by daotoad** [comment] 2022-09-28 00:15
I don't want to fork this repo and submit a PR, but I think the problem is here:  https://github.com/mdn/dom-examples/blob/main/service-worker/simple-service-worker/app.js#L7

The path to the service worker script is absolute instead of relative.  Should be a one character change.

**Comment by caugner** [comment] 2023-10-12 16:09
Already fixed by https://github.com/mdn/dom-examples/pull/179.

**Closed by caugner** 2023-10-12 16:09 UTC
Labels: bug, area: service-worker
